version: "3.9"


services:
  api:
      restart: on-failure:5
      build:
        context: .
        dockerfile: Dockerfile
      env_file: .env
      depends_on:
        - redis
      ports:
        - "${API_PORT}:${API_PORT}"

  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: on-failure:5
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
volumes:
  data:
