definitions:
  ip.IPData:
    properties:
      city:
        type: string
      country:
        type: string
      hostname:
        type: string
      ip:
        type: string
      loc:
        type: string
      org:
        type: string
      timezone:
        type: string
    type: object
info:
  contact: {}
paths:
  /ip/{ip}:
    get:
      consumes:
      - application/json
      description: get IP address info
      parameters:
      - description: IP Address
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ip.IPData'
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: getIPinfo
      tags:
      - ip info
swagger: "2.0"
