basePath: /api/v1
definitions:
  auth.MessageResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    required:
    - code
    - message
    type: object
  auth.UserJWT:
    properties:
      code:
        type: integer
      expire:
        type: string
      token:
        type: string
    required:
    - code
    - expire
    - token
    type: object
  ip.IPData:
    properties:
      city:
        type: string
      country:
        type: string
      hostname:
        type: string
      ip:
        type: string
      loc:
        type: string
      org:
        type: string
      timezone:
        type: string
    type: object
  ipinfo.MessageResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    required:
    - code
    - message
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
    url: http://t.me/onorridg
  title: IP Address API
  version: "1.0"
paths:
  /auth/password:
    patch:
      consumes:
      - multipart/form-data
      description: password
      parameters:
      - in: formData
        name: username
        required: true
        type: string
        x-order: "0"
      - in: formData
        name: password
        required: true
        type: string
        x-order: "1"
      - in: formData
        name: new_password
        required: true
        type: string
        x-order: "3"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ipinfo.MessageResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/ipinfo.MessageResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/ipinfo.MessageResponse'
      summary: Password reset
      tags:
      - auth
  /auth/sign-in:
    post:
      consumes:
      - multipart/form-data
      description: sign-in
      parameters:
      - in: formData
        name: username
        required: true
        type: string
        x-order: "0"
      - in: formData
        name: password
        required: true
        type: string
        x-order: "1"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.UserJWT'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/auth.MessageResponse'
      summary: Sign-in
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - multipart/form-data
      description: sign-up
      parameters:
      - in: formData
        name: username
        required: true
        type: string
        x-order: "0"
      - in: formData
        name: password
        required: true
        type: string
        x-order: "1"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ipinfo.MessageResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/ipinfo.MessageResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/ipinfo.MessageResponse'
      summary: Sign-up
      tags:
      - auth
  /ip/{ip}:
    get:
      consumes:
      - application/json
      description: get IP address info
      parameters:
      - description: IP Address
        in: path
        name: ip
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ip.IPData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ipinfo.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/ipinfo.MessageResponse'
      security:
      - ApiKeyAuth: []
      summary: IP address info
      tags:
      - ip
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
